name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: "AWS region"
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    environment: development
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .deployments/aws

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: â˜ï¸ Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.12.2

      - name: ğŸ” Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ inputs.aws_region || secrets.AWS_REGION }}

      - name: ğŸ“ Write tfvars from secret
        run: |
          echo 'ecr_registry = "${{ secrets.ECR_REGISTRY }}"' > ci.auto.tfvars

      - name: ğŸªµ Enable Terraform Debug Logging
        run: |
          echo "TF_LOG=INFO" >> $GITHUB_ENV
          echo "TF_LOG_PATH=terraform-debug.log" >> $GITHUB_ENV

      - name: ğŸ§ª Terraform Init
        run: terraform init -input=false -no-color

      - name: ğŸ“‹ Terraform Plan
        run: terraform plan -input=false -no-color -out=tfplan.binary

      - name: ğŸš€ Terraform Apply
        run: terraform apply -input=false -no-color tfplan.binary

      - name: ğŸ“¤ Upload Terraform Debug Logs (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-debug
          path: .deployments/aws/terraform-debug.log
