name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: "AWS region (default: ap-southeast-1)"
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    environment: development
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .deployments/aws
    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: â˜ï¸ Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.12.2

      - name: ğŸ” Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ inputs.aws_region || secrets.AWS_REGION }}

      - name: ğŸ“ Write tfvars from secret
        run: |
          echo 'ecr_registry = "${{ secrets.ECR_REGISTRY }}"' > ci.auto.tfvars

      - name: ğŸ§ª Terraform Init
        run: terraform init -input=false -no-color

      - name: âš ï¸ Terraform Destroy
        run: terraform destroy -auto-approve
